# https://taskfile.dev

version: '3'
tasks:
  templ-gen:
    cmds:
      - templ generate
    silent: true

  nebula:build:
    dir: .
    cmds:
      - devbox run build
    silent: true

  nebula:publish:
    dir: .
    cmds:
      - devbox run publish
    silent: true

  esclient:build:
    dir: ./libs/es-client
    cmds:
      - devbox run build
    silent: true

  esclient:publish:
    dir: ./libs/es-client
    cmds:
      - task: esclient:bump
      - devbox run publish
    silent: true

  esclient:bump:
    dir: ./libs/es-client
    cmds:
      - pnpm version patch
      - git add package.json
      - git commit -m "chore: bump version to {{.VERSION}} [skip ci]"
      - git push
    silent: true
