# https://taskfile.dev

version: '3'
tasks:
  templ-gen:
    cmds:
      - templ generate
    silent: true

  nebula:build:
    dir: .
    cmds:
      - devbox run build
    silent: true

  nebula:publish:
    dir: .
    cmds:
      - devbox run publish
    silent: true

  esclient:build:
    dir: ./libs/es-client
    cmds:
      - devbox run build
    silent: true

  esclient:publish:
    dir: ./libs/es-client
    cmds:
      - devbox run publish
    silent: true
