# This workflow will create a GitHub release every time a tag is pushed
name: Deploy CDN WebComponents

on:
  push:
    branches:
      - "master"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Git Config
        run: |
          bun install
          git config user.name "Prad N."
          git config user.email "prad@sonr.io"


      - name: Build
        run: bun run build

      - name: 'Automated Version Bump and Release'
        run: |
          git add .
          git commit -m "chore: update build artifacts [skip ci]" || echo "No changes to commit"
          npm version patch
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
